n = int(input('\nDigite um número para obtermos sua tabuada: '))
print('')
print('0 X ', n, '= ', (0 * n))
print('1 X ', n, '= ', (1 * n))
print('2 X ', n, '= ', (2 * n))
print('3 X ', n, '= ', (3 * n))
print('4 X ', n, '= ', (4 * n))
print('5 X ', n, '= ', (5 * n))
print('6 X ', n, '= ', (6 * n))
print('7 X ', n, '= ', (7 * n))
print('8 X ', n, '= ', (8 * n))
print('9 X ', n, '= ', (9 * n))
print('10 X ', n, '= ', (10 * n))